# VoxBridge Configuration

# Speech-to-Text (STT) Configuration
stt:
  engine: "placeholder"
  model: "placeholder-model"
  language_codes: ["en-US", "fr-FR", "se-SE"]
  sample_rate: 16000
  timeout: 5

# Translation Configuration
translation:
  engine: "placeholder"
  model: "placeholder-model"
  source_languages: ["en", "fr", "se"]
  target_languages: ["en", "fr", "se"]
  batch_size: 32

# Text-to-Speech (TTS) Configuration
tts:
  engine: "placeholder"
  voice_profiles:
    - language: "en-US"
      gender: "female"
      name: "placeholder-voice-1"
    - language: "fr-FR"
      gender: "male"
      name: "placeholder-voice-2"
  audio_format: "mp3"
  sample_rate: 24000

# Streaming Configuration
streaming:
  protocol: "websocket"
  buffer_size: 4096
  max_connections: 100
  timeout: 300

# Admin Configuration
admin:
  users:
    - username: "admin"
      password: "placeholder-password"
      role: "admin"
    - username: "user"
      password: "placeholder-password"
      role: "viewer"
  session_timeout: 3600
  log_level: "info"
