services:
  stt:
    build:
      context: .
      dockerfile: docker/stt/Dockerfile
    environment:
      - SERVICE_NAME=stt
    volumes:
      - ./config:/app/config:ro

  translation:
    build:
      context: .
      dockerfile: docker/translation/Dockerfile
    environment:
      - SERVICE_NAME=translation
    volumes:
      - ./config:/app/config:ro

  tts:
    build:
      context: .
      dockerfile: docker/tts/Dockerfile
    environment:
      - SERVICE_NAME=tts
    volumes:
      - ./config:/app/config:ro

  streaming:
    build:
      context: .
      dockerfile: docker/streaming/Dockerfile
    environment:
      - SERVICE_NAME=streaming
    ports:
      - "1935:1935" # RTMP
      - "8080:8080" # HTTP

  admin:
    build:
      context: .
      dockerfile: docker/admin/Dockerfile
    environment:
      - SERVICE_NAME=admin
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config:ro
